### ISSUE TITLE
How are images referenced from jsx?

### ISSUE THREAD

**Issue by jardakotesovec** [petehunt/webpack-howto#11]
Webpack automatically detects `url("img/smile.png")` statements in css files, so no need to put require there. But I am wondering, how nicely reference images inside jsx, when I am using react.

its certainly possible like this:

```
var smileURL = require('img/smile.png');
return <div><img src={smileURL}</div>
```

 but it would be very nice if its possible to reference it directly in src tag:

```
return <div><img src="img/smile.png"</div>
```

So just wondering whats your take on this. Thank you!

**Comment by footnoteapplication** [comment]
Thanks @jardakotesovec 

Though if you're copy and pasting this, it's missing a closing bracket.. 

<img src={require('../../../images/logo.png')}
