### ISSUE TITLE
How to create split points with common chunks

### ISSUE THREAD

**Issue by antonmoiseev** [petehunt/webpack-howto#20]
There is [an example](https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points) of multiple entry points sharing chunks, but is it possible to create split points that have chunks in common? I've extended @codeboyim's [sample app](https://github.com/codeboyim/webpack-sample) discussed in issue #8, here is [my version](https://github.com/antonmoiseev/webpack-sample).

The main changes:

1. Created new `lib.js` file required by both modules:
  ```js
  // feed.js (the same in profile.js)
  var lib = require('./lib');
  ```

2. Added third parameter to `require.ensure()` invocation to be able to reference these modules in `webpack.config.js` file:
  ```js
  require.ensure([], function () {
      require('./feed').show();
  }, 'feed');
  //...
  require.ensure([], function () {
      require('./profile').show();
  }, 'profile');
  ```

3. Configured `CommonsChunkPlugin`:
  ```js
  plugins: [
      new webpack.optimize.CommonsChunkPlugin('commons.js', ['feed', 'profile'])
  ]
  ```

Here is the full [diff](https://github.com/antonmoiseev/webpack-sample/commit/53729f4c57ea16fd6214f32c1f4427dfe81a1640).

However both `main.js` and `common.js` generated files contain the module system and chunks loading logic, so the app doesn't work.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/tree/master/examples/extra-async-chunk

**Comment by antonmoiseev** [comment]
Thank you, @sokra!

For those who might be interested in the complete example, here is updated webpack config file:
```js
var webpack = require('webpack');

module.exports = {
    entry: './main',
    output: {
        path: 'build',
        filename: '[name].js',
        publicPath: 'build/'
    },

    plugins: [
      new webpack.optimize.CommonsChunkPlugin({name: 'main', async: true})
    ]
};
```

Notice configuration of `CommonsChunkPlugin`.
