### ISSUE TITLE
Require stylesheet

### ISSUE THREAD

**Issue by MickCoelho** [petehunt/webpack-howto#24]
Requiring stylesheets from server like that won't work:
`require('../styles/styles.css');`

Even though we're using loaders (https://github.com/petehunt/webpack-howto/#5-stylesheets-and-images). Am I right?

**Comment by nkbt** [comment]
@MickCoelho I am actually doing this with no problems. Even SASS. See example at https://github.com/packetloop/angular-webpack

```javascript
 module: {
  loaders: [
    {test: /\.sass$/, loader: 'style!css!sass?indentedSyntax=true'},
    {test: /\.(png|jpg)$/, loader: 'url?limit=32768'},
    {test: /\.html$/, loader: 'ng-cache?prefix=[dir]/[dir]'},
    {test: /\.haml$/, loader: 'hamlc-loader'}
  ],
```

So if you want simple css:

```javascript
 module: {
  loaders: [
    {test: /\.css$/, loader: 'style!css'}
  ],
```

And you will need `style-loader` and `css-loader` accordingly

**Comment by MickCoelho** [comment]
@nkbt I guess it's due to the fact that I'm using Reactjs which may not support it :/

**Comment by MickCoelho** [comment]
@nkbt I guess it's due to the fact that I'm using Reactjs which may not support it :/
Seems to work fine on the client, but throw me errors on the server.

**Comment by nkbt** [comment]
@MickCoelho ah I see. SO you are rendering on the server then. `style-loader` injects `<style>` tag in runtime. So it should not work server-side. You can load css as just text and then inject it manually of course. Bu I'm not completely sure it is a good idea. As soon as you are using React, I'd recommend to look at something like https://github.com/jsstyles/jss or any other `CSS as JS` solution.

**Comment by MickCoelho** [comment]
@nkbt wanted to avoid that and use proper css files, but it seems like it's the only solution for now. Thanks!

**Comment by Bear-Foot** [comment]
@MickCoelho 
I ran into this issue some days ago and I got it solved pretty easily.

You can't indeed use Node's native require system to require CSS. Therefore, I built my server application with webpack too. Using webpack to build a bundle required afterward by a classic Node file.

Not sure if I made myself clear, so let me know if you need an example (the one I have is not ready to show).

TIP : remove node_modules/ from your server side bundle. 
http://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by MickCoelho** [comment]
@Bear-Foot Thanks for the tip!
I finally ended up building my own skeleton and now I can get stylesheets on the server-side as well: https://github.com/MickCoelho/react-isomorphic

What I'm doing on the `server.js` is basically loading the `.css` files (using `fs.readFileSync()`) relative to the current page, then I inline them onto the generated html page.
