### ISSUE TITLE
Require('file.css') messing with Jest tests

### ISSUE THREAD

**Issue by cirocosta** [petehunt/webpack-howto#6]
Hey guys!

Firstly i'd like to say that webpack really impressed me, what a cool project! And thanks for this howto, very helpful :+1: 

I followed some webpack examples (and what is presented in this how-to) and then set up a little project following the structure of [petehunt/react-touch](https://github.com/petehunt/react-touch). When i started adding some tests i came up with problems with some of the files that contained `require('./MyComponent.css')` - in a `MyComponent.jsx`, for example.

When removing that `.css` dependency i was able to proceed with the test (running them with Jest).

Am i doing something wrong (testing a component that required a .css - should i modularize more?) or there is a pattern/plugin for dealing with this? Maybe some help on this would be great for others that encounter the same issue :neckbeard: 

Thanks!

_i thought this was the best place to ask as i think those who are comming to webpack - like me - might search a question like that here. Please tell me if this was not the right place!_

**Comment by tomatau** [comment]
different solution here

jest.scriptPreprocessor:
```
module.exports = {
  process: function(src, path) {
    if (path.match(/\.es6?$/))
      src = es6tr.run({src: src}).src
    if (path.match(/\.jsx?$/))
      src = ReactTools.transform(src, {harmony: true});
    if (path.match(/\.less?$/)) {
      src = {}
    }
    return src
  }
};
```
